name: getx_template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  dio: ^5.3.2
  encrypted_shared_preferences: ^3.0.1
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-Medium.ttf
        - asset: fonts/OpenSans-Regular.ttf
